const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const N=[['До','C4',261.63],['Ре','D4',293.66],['Ми','E4',329.63],['Фа','F4',349.23],['Соль','G4',392],['Ля','A4',440],['Си','B4',493.88]];
const names=['Первые 5 нот','Ритм и пульс','Правильная посадка','Ноты на клавиатуре','До и Ре','Ми и Фа','Соль и Ля','Си и октава','Пять пальцев','Первое упражнение','Чередование пальцев','Ровный звук','Сильная и слабая доля','Счёт до четырёх','Паузы','Длинные ноты','Правая рука','Левая рука','Обе руки','Переход через палец','Гамма До мажор','Арпеджио','Аккорд До','Аккорд Фа','Аккорд Соль','Трезвучия','I-IV-V','Простая мелодия','Мелодия правой рукой','Бас левой рукой','Мелодия и аккомпанемент','Ритм 2/4','Ритм 3/4','Ритм 4/4','Восьмые ноты','Шестнадцатые ноты','Синкопа','Точка после ноты','Такт и размер','Динамика','Легато','Стаккато','Акценты','Педаль','Смена аккордов','Арпеджио левой руки','Басовые ноты','Простая песня','Чтение нот','Скрипичный ключ','Нотный стан','Интервалы','Секунда','Терция','Кварта','Квинта','Секста','Септима','Октава','Мажор','Минор','Тон и полутон','Гамма Соль мажор','Гамма Фа мажор','Гамма Ре мажор','Гамма Ля минор','Аккорды минор','Каденция','II-V-I','Популярные аккорды','Паттерн левой руки','Паттерн правой руки','Остинато','Баланс рук','Метроном','Игра медленно','Постепенное ускорение','Игра без остановок','Запоминание мелодии','Игра на слух','Повтор фразы','Четырёхтактовая фраза','Восьмитактовая фраза','Простая импровизация','Импровизация на пяти нотах','Блюзовая гамма','Блюзовый ритм','Простой блюз','Джазовый аккорд','Вальс','Баллада','Поп-аккомпанемент','Рок-аккомпанемент','Музыка из игр','Классическая мелодия','Народная мелодия','Чтение с листа 1','Чтение с листа 2','Чтение с листа 3','Игра двумя руками 1','Игра двумя руками 2','Игра двумя руками 3','Аккордовая песня 1','Аккордовая песня 2','Аккордовая песня 3','Финальная практика 1','Финальная практика 2','Финальная практика 3','Итоговая песня','Финальный тест','Ты умеешь играть!'];
let st=JSON.parse(localStorage.getItem('pq3')||'{"xp":0,"lesson":0,"streak":0}'),ctx=null,an=null,stream=null,run=false,target=0,current=null,step=0,songRun=false;

function save(){localStorage.setItem('pq3',JSON.stringify(st));$('#xpText').textContent=st.xp+' / 100 XP';$('#xpBar').style.width=Math.min(100,st.xp)+'%';$('#streak').textContent=st.streak;$('#progressText').textContent=`Урок ${Math.min(115,st.lesson+1)} из 115`;$('#continueTitle').textContent=names[Math.min(114,st.lesson)];$('#continueMeta').textContent=`Интерактивная практика · Урок ${st.lesson+1} из 115`}
function show(id){$$('.screen').forEach(x=>x.classList.toggle('active',x.id===id));$$('nav button').forEach(x=>x.classList.toggle('active',x.dataset.go===id));scrollTo(0,0)}
$$('[data-go]').forEach(b=>b.onclick=()=>show(b.dataset.go));

function lessons(){ $('#lessonsList').innerHTML=names.map((n,i)=>`<button class="lessonRow ${i<st.lesson?'done':''}" data-i="${i}"><i>${i<st.lesson?'✓':i+1}</i><div><small>УРОК ${i+1} · ${i<10?'5':'10'} МИН</small><h3>${n}</h3><p>Доступно · интерактивная практика</p></div><span>›</span></button>`).join('');$$('.lessonRow').forEach(b=>b.onclick=()=>openLesson(+b.dataset.i))}
function openLesson(i){let n=N[i%7];$('#lessonNumber').textContent='УРОК '+(i+1);$('#lessonTitle').textContent=names[i];$('#lessonHeading').textContent=names[i];$('#lessonLevel').textContent='УРОВЕНЬ '+(Math.floor(i/10)+1);$('#lessonDescription').textContent='Посмотри на ноту, сыграй её на синтезаторе и получи проверку микрофоном.';$('#lessonVisual').innerHTML=`<div class="bigNote">♪</div><b>${n[0]}</b><small>${n[1]} · ${n[2]} Hz</small>`;$('#lessonSteps').innerHTML='<div>① Посмотри на ноту</div><div>② Сыграй её</div><div>③ Получи проверку</div>';$('#lessonStart').onclick=()=>startLesson(i);show('lesson')}
$('#continueLesson').onclick=()=>openLesson(st.lesson);

async function mic(){if(an)return true;try{stream=await navigator.mediaDevices.getUserMedia({audio:{echoCancellation:false,noiseSuppression:false,autoGainControl:false,channelCount:1}});ctx=new(window.AudioContext||window.webkitAudioContext)();await ctx.resume();let src=ctx.createMediaStreamSource(stream);an=ctx.createAnalyser();an.fftSize=4096;an.smoothingTimeConstant=.03;src.connect(an);$('#micStatus').textContent='● Микрофон работает';$('#micBtn').textContent='✓ Микрофон включён';return true}catch(e){$('#micStatus').textContent='Разреши микрофон в Safari';return false}}
$('#micBtn').onclick=mic;
function pitch(){if(!an)return null;let b=new Float32Array(an.fftSize);an.getFloatTimeDomainData(b);let m=b.reduce((a,v)=>a+v,0)/b.length,r=Math.sqrt(b.reduce((a,v)=>a+(v-m)**2,0)/b.length);if(r<.005)return null;let lo=Math.floor(ctx.sampleRate/900),hi=Math.floor(ctx.sampleRate/90),bl=0,bs=-1;for(let l=lo;l<=hi;l++){let s=0;for(let i=0;i<b.length-l;i+=2)s+=(b[i]-m)*(b[i+l]-m);if(s>bs){bs=s;bl=l}}if(!bl)return null;let f=ctx.sampleRate/bl;return f>90&&f<1000?f:null}
function near(f){let bi=0,bd=1e9;N.forEach((n,i)=>{let d=Math.abs(1200*Math.log2(f/n[2]));if(d<bd){bd=d;bi=i}});return[bi,Math.round(1200*Math.log2(f/N[bi][2]))]}
function award(){st.xp=Math.min(100,st.xp+3);st.streak=Math.max(1,st.streak);save()}
let lrun=false,li=0;
async function startLesson(i){li=i;if(!await mic())return;let n=N[i%7];$('#lessonTarget').textContent=n[0];$('#lessonTargetLatin').textContent=n[1];$('#lessonFeedback').textContent='Сыграй '+n[0];$('#lessonPracticeBtn').textContent='▶ Старт упражнения';lrun=false;show('lessonPractice')}
function lframe(){if(!lrun)return;let f=pitch();if(f){let[i,c]=near(f);$('#lessonDetected').textContent=N[i][0];$('#lessonCents').textContent=(c>=0?'+':'')+c+' cents';if(i===li%7&&Math.abs(c)<=60){lrun=false;award();$('#lessonFeedback').textContent='✓ Правильно! Урок выполнен';$('#lessonPracticeBtn').textContent='✓ Готово';setTimeout(()=>{st.lesson=Math.max(st.lesson,Math.min(114,li+1));save();lessons();show('course')},850)}}requestAnimationFrame(lframe)}
$('#lessonPracticeBtn').onclick=async()=>{if(!await mic())return;lrun=!lrun;$('#lessonPracticeBtn').textContent=lrun?'■ Остановить':'▶ Старт упражнения';if(lrun)lframe()};$('#lessonBack').onclick=()=>show('lesson');

let pRun=false;function pframe(){if(!pRun)return;let f=pitch();if(f){let[i,c]=near(f);$('#detected').textContent=N[i][0];$('#cents').textContent=(c>=0?'+':'')+c+' cents';if(i===target&&Math.abs(c)<=60){award();$('#feedback').textContent='✓ Отлично!';setTimeout(()=>{target=Math.floor(Math.random()*7);$('#targetNote').textContent=N[target][0];$('#targetLatin').textContent=N[target][1]},500)}}requestAnimationFrame(pframe)}
$('#exerciseBtn').onclick=async()=>{if(!await mic())return;pRun=!pRun;$('#exerciseBtn').textContent=pRun?'■ Остановить':'▶ Старт упражнения';if(pRun){target=Math.floor(Math.random()*7);$('#targetNote').textContent=N[target][0];$('#targetLatin').textContent=N[target][1];pframe()}};

const S=[
['🌿','Spring','Stardew Valley · Лёгкая',[329.63,392,440,392,329.63,293.66,261.63,329.63],[2,4,5,4,2,1,0,2]],
['✨','Ode to Joy','Классика · Очень лёгкая',[329.63,329.63,349.23,392,392,349.23,329.63,293.66],[2,2,3,4,4,3,2,1]],
['🌹','Für Elise','Классика · Средняя',[329.63,311.13,329.63,311.13,329.63,246.94,293.66,261.63],[2,1,2,1,2,0,1,0]],
['☕','Autumn Leaves','Джаз · Средняя',[329.63,392,440,493.88,440,392,329.63],[2,4,5,6,5,4,2]],
['❄️','Stardew Valley — Winter','Игры · Средняя',[261.63,293.66,349.23,392,349.23,293.66],[0,1,3,4,3,1]],
['🌙','Clair de Lune','Классика · Средняя',[261.63,329.63,392,523.25,392,329.63],[0,2,4,6,4,2]],
['🎹','Gymnopédie No. 1','Классика · Лёгкая',[261.63,293.66,329.63,392,329.63,293.66],[0,1,2,4,2,1]],
['🌊','River Flows in You','Современная · Средняя',[329.63,392,493.88,440,392,329.63],[2,4,6,5,4,2]],
['🦋','Comptine d’un autre été','Классика · Средняя',[329.63,392,493.88,392,329.63,293.66],[2,4,6,4,2,1]],
['🎬','Interstellar Theme','Кино · Средняя',[261.63,329.63,392,329.63,261.63,196],[0,2,4,2,0]],
['⭐','Harry Potter Theme','Кино · Средняя',[392,493.88,523.25,392,493.88,415.3],[4,6,7,4,6,5]],
['🌼','Canon in D','Классика · Лёгкая',[293.66,329.63,392,440,493.88,440],[1,2,4,5,6,5]],
['🎷','Blue Monk','Джаз · Средняя',[261.63,293.66,349.23,392,349.23,293.66],[0,1,3,4,3,1]],
['🌧️','Kiss the Rain','Современная · Средняя',[329.63,392,440,493.88,440,392],[2,4,5,6,5,4]],
['🏡','Merry Go Round of Life','Классика · Средняя',[392,440,493.88,523.25,493.88,440,392],[4,5,6,7,6,5,4]]
];
function renderSongs(q=''){ $('#songsList').innerHTML=S.filter(s=>(s[1]+s[2]).toLowerCase().includes(q.toLowerCase())).map((s,i)=>`<button class="song" data-s="${i}"><div class="cover">${s[0]}</div><div><h3>${s[1]}</h3><p>${s[2]}</p></div><span>Учить ›</span></button>`).join('');$$('.song').forEach(b=>b.onclick=()=>openSong(+b.dataset.s))}
$('#search').oninput=e=>renderSongs(e.target.value);
function openSong(i){current=S[i];step=0;$('#songEmoji').textContent=current[0];$('#songTitle').textContent=current[1];$('#songGuideTitle').textContent=current[1];$('#songMeta').textContent=current[2];renderSong();show('songGuide')}
function renderSong(){let idx=current[4][step],n=N[idx];$('#guideBar').style.width=(step/current[4].length*100)+'%';$('#guideProgressText').textContent=`Нота ${step+1} из ${current[4].length}`;$('#fallLeft').textContent=step%3===0?'●':'';$('#fallRight').textContent=step%3?`♪`:'';$('#leftTarget').textContent=step%3===0?'До':'—';$('#rightTarget').textContent=n[0];$('#chordTarget').textContent=step%4===0?'C':'—';$('#chordNotes').textContent=step%4===0?'До · Ми · Соль':'Мелодическая нота';$('#guideFeedback').textContent='Сыграй подсвеченную ноту';$('#guideDetected').textContent='Готов';document.querySelectorAll('.pkey').forEach(x=>x.classList.remove('target'));let k=document.querySelector(`.pkey[data-i="${idx}"]`);if(k)k.classList.add('target')}
async function sframe(){if(!songRun)return;let f=pitch();if(f){let[i,c]=near(f),wanted=current[4][step];$('#guideDetected').textContent=N[i][0];$('#guideCents').textContent=(c>=0?'+':'')+c+' cents';document.querySelectorAll('.pkey').forEach(x=>x.classList.remove('hit'));let k=document.querySelector(`.pkey[data-i="${i}"]`);if(k)k.classList.add('hit');if(i===wanted&&Math.abs(c)<=65){award();$('#guideFeedback').textContent='✓ Правильно!';songRun=false;setTimeout(()=>{if(step<current[4].length-1){step++;renderSong()}else{$('#guideFeedback').textContent='🎉 Песня выучена! Теперь попробуй режим «Песня целиком».';$('#guideStart').textContent='✓ Готово'}},550)}}requestAnimationFrame(sframe)}
$('#guideStart').onclick=async()=>{if(!await mic())return;if($('#guideStart').textContent.includes('Готово'))return;songRun=!songRun;$('#guideStart').textContent=songRun?'■ Остановить':'▶ Начать песню';if(songRun)sframe()};
function sound(s){if(!ctx)ctx=new(window.AudioContext||window.webkitAudioContext)();ctx.resume();s[3].forEach((f,i)=>setTimeout(()=>{let o=ctx.createOscillator(),g=ctx.createGain();o.frequency.value=f;g.gain.setValueAtTime(.001,ctx.currentTime);g.gain.exponentialRampToValueAtTime(.15,ctx.currentTime+.03);g.gain.exponentialRampToValueAtTime(.001,ctx.currentTime+.38);o.connect(g);g.connect(ctx.destination);o.start();o.stop(ctx.currentTime+.4)},i*420))}
$('#songPlay').onclick=()=>sound(current);$('#songBack').onclick=()=>show('songs');
function piano(){let p=$('#piano');p.innerHTML=N.map((n,i)=>`<div class="pkey" data-i="${i}"><span>${n[0]}</span></div>`).join('')}piano();
save();lessons();renderSongs();
