const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const NOTE_NAMES=['до','ре','ми','фа','соль','ля','си'];
const TECH=['до','ре','ми','фа','соль','ля','си'];
const ROOTS=['до','ре','ми','фа','соль','ля','си'];
const KEY_MIDI={до:60,ре:62,ми:64,фа:65,соль:67,ля:69,си:71};
const LESSON_TITLES=[
'Первые семь нот','Как устроены белые клавиши','Правильная посадка','Положение рук','Первые пять пальцев','Находим ноты быстрее','Ритм: считаем 1–2–3–4','Ровный звук','Первый ритмический рисунок','Первые короткие мелодии',
'До–ре–ми','Ми–ре–до','До–ми–соль','Пять нот без остановки','Слушаем и повторяем','Сильная и слабая доля','Паузы','Длительности нот','Метроном без страха','Мини-мелодия №1',
'Правая рука: пять пальцев','Левая рука: пять пальцев','Перенос руки','Прыжки через ноты','Короткие фразы','Легато','Стаккато','Динамика: тише и громче','Акценты','Мини-мелодия №2',
'Читаем ноты на стане','Скрипичный ключ','Басовый ключ','Ноты правой руки','Ноты левой руки','Ориентиры: до и соль','Ритм по нотам','Сыграй с листа','Читаем двумя руками','Мини-мелодия №3',
'Что такое аккорд','До мажор','Соль мажор','Фа мажор: аккорд','Ре мажор','Ля минор','Ми минор','Ре минор','Переходы между аккордами','Четыре аккорда',
'Мажор и минор','Форма мажорного аккорда','Форма минорного аккорда','Уменьшённый аккорд','Sus2','Sus4','Обращения аккордов','Как не прыгать рукой','Аккордовая последовательность','Аккорды под мелодию',
'Гамма до мажор','Гамма соль мажор','Гамма ре мажор','Гамма ля минор','Гамма ми минор','Гамма фа мажор','Гамма си-бемоль мажор','Гаммы: аппликатура','Гаммы в обе стороны','Гамма как упражнение',
'Арпеджио','Разложенный аккорд','Переход через большой палец','Независимость пальцев','Равномерность','Ускоряем без ошибок','Метроном и скорость','Динамика в гаммах','Арпеджио двумя руками','Техническая мини-связка',
'Левая рука как аккомпанемент','Басовая нота + аккорд','Вальсовый ритм','Бас–аккорд','Остинато','Левая рука в песне','Правая мелодия + левая гармония','Баланс рук','Простое сопровождение','Мини-композиция',
'Синкопа','Триоли','Ритмические связки','Педаль: зачем она','Педаль без грязи','Фразировка','Музыкальные предложения','Как запоминать произведение','Как тренироваться 15 минут','Подготовка к песням',
'Песня: простая мелодия','Песня: Spring — Stardew Valley','Песня: аккордовый рисунок','Песня: правая рука','Песня: левая рука','Песня: соединяем руки','Песня: игра с метрономом','Песня: динамика','Песня: игра без подсказок','Песня: мини-выступление',
'Итоговая песня — Spring: разбор','Итоговая песня — Spring: правая рука','Итоговая песня — Spring: левая рука','Итоговая песня — Spring: аккорды','Финал: сыграй Spring целиком'
];
// Ровно 115 уроков: массив выше содержит 115 названий.
const SPECIAL={
1:{type:'notes',theory:'Сегодня без лишней теории: научимся узнавать семь белых нот и находить их на клавиатуре.',practice:'Ищи подсвеченную ноту и сыграй её. Семь шагов — до, ре, ми, фа, соль, ля, си.',visual:'keyboard'},
3:{type:'seat',theory:'Сядь устойчиво, без напряжения. Клавиатура должна быть перед тобой, плечи свободны, кисти не проваливаются. Не пытайся держать спину как солдат — цель в свободном положении.',practice:'Сделай короткую проверку посадки по пяти пунктам и только потом сыграй три спокойные ноты.',visual:'seat'},
4:{type:'hands',theory:'Пальцы мягко согнуты, кисть продолжает линию предплечья. Не зажимай пальцы и не дави на клавиши всей рукой.',practice:'Поставь обе руки на пять соседних белых клавиш и по очереди сыграй каждую.',visual:'hands'},
22:{type:'hands',theory:'Левая рука получает такие же номера пальцев, как правая, но счёт идёт с мизинца: 5–4–3–2–1.',practice:'Сыграй пять соседних нот левой рукой вперёд и обратно.',visual:'hands'},
41:{type:'chord',theory:'Аккорд — несколько нот, звучащих одновременно. Начинаем с трёх нот.',practice:'Сыграй показанные три клавиши одновременно. Затем повтори с другой рукой.',visual:'chord'},
42:{type:'chord',theory:'До мажор: до–ми–соль. Это один из главных аккордов для старта.',practice:'Нажми три подсвеченные клавиши одновременно и отпусти их вместе.',visual:'chord'},
51:{type:'chord',theory:'Мажор и минор отличаются прежде всего средней нотой. В миноре она ниже на полтона.',practice:'Сравни одну и ту же основу в мажоре и миноре, затем сыграй случайный аккорд.',visual:'chord'},
56:{type:'chord',theory:'Sus4 заменяет среднюю ступень на ноту на один тон выше. Звук получается открытым и ожидающим разрешения.',practice:'Сыграй случайный sus4 аккорд.',visual:'chord'},
57:{type:'chord',theory:'Обращение меняет порядок нот, но аккорд остаётся тем же. Это позволяет меньше двигать рукой.',practice:'Сравни основной вид и обращение одного аккорда.',visual:'chord'},
64:{type:'scale',theory:'Фа мажор: фа–соль–ля–си-бемоль–до–ре–ми–фа. Здесь одна чёрная клавиша: си-бемоль.',practice:'Сначала сыграй гамму правой рукой медленно, затем обратно. Потом попробуй левой.',visual:'scale'},
68:{type:'scale',theory:'Гамма — последовательность соседних ступеней. Аппликатура помогает руке проходить через всю октаву без неудобного растяжения.',practice:'Сыграй гамму с подсказкой пальцев, не ускоряясь.',visual:'scale'},
71:{type:'arpeggio',theory:'Арпеджио — ноты аккорда, сыгранные по очереди. Это база для красивого сопровождения.',practice:'Сыграй до–ми–соль–ми и повтори ровно четыре раза.',visual:'arpeggio'},
76:{type:'left',theory:'Левая рука может быть не только второй мелодией. Её главная задача в сопровождении — дать опору и гармонию.',practice:'Сыграй басовую ноту левой рукой, затем аккорд правой.',visual:'hands'},
88:{type:'pedal',theory:'Педаль продлевает звук. Меняй её вместе со сменой гармонии, иначе звук превращается в кашу.',practice:'Сыграй два аккорда с педалью: нажми педаль после аккорда и отпусти перед следующим.',visual:'pedal'},
91:{type:'practice',theory:'Короткие регулярные занятия полезнее редких длинных. Сегодня учимся заниматься 15 минут с конкретной целью.',practice:'Сделай 3 минуты разминки, 5 минут техники, 5 минут песни и 2 минуты свободной игры.',visual:'timer'},
101:{type:'song',theory:'Spring — The Valley Comes Alive — хорошая цель для курса: мелодия, аккордовая опора и работа обеих рук.',practice:'Послушай пример, затем разберём маленький фрагмент правой рукой.',visual:'song'},
111:{type:'song',theory:'Финальная песня курса — Spring (The Valley Comes Alive). Сначала разбираем правую руку, затем левую, затем соединяем.',practice:'Послушай пример и сыграй первый короткий фрагмент по подсказке.',visual:'song'},
120:{type:'final',theory:'Если ты дошёл сюда, у тебя уже есть база: ноты, ритм, аккорды, гаммы, две руки и работа с песней.',practice:'Сыграй финальную песню целиком в своём темпе.',visual:'song'}
};
const SONGS=[
{id:'spring',name:'Spring — The Valley Comes Alive',artist:'Stardew Valley',level:'Средняя',video:'8sh31m-QBvU',desc:'Пиано-версия и разбор. Оригинал написан ConcernedApe.',tags:['две руки','аккорды','мелодия']},
{id:'bigworld',name:'Spring — It’s A Big World Outside',artist:'Stardew Valley',level:'Средняя',video:'1VmmCGyGo_c',desc:'Пиано-разбор мелодии из весеннего саундтрека.',tags:['мелодия','ритм']},
{id:'horseradish',name:'Spring — Wild Horseradish Jam',artist:'Stardew Valley',level:'Средняя',video:'z5GXVUV3wIg',desc:'Ещё одна весенняя тема в пиано-аранжировке.',tags:['мелодия','две руки']}
];
let S=JSON.parse(localStorage.getItem('pianoLearningV4')||'{"completed":{},"xp":0,"streak":0,"last":"","todayXP":0}');
function day(){return new Date().toLocaleDateString('en-CA')}
function touch(){const d=day();if(S.last!==d){if(S.last){const diff=Math.round((new Date(d)-new Date(S.last))/86400000);S.streak=diff===1?S.streak+1:1}else S.streak=1;S.last=d;S.todayXP=0}saveState()}
function saveState(){localStorage.setItem('pianoLearningV4',JSON.stringify(S))}
function dayWord(n){n=Math.abs(n)%100;const x=n%10;return n>10&&n<20?'дней':x===1?'день':x>=2&&x<=4?'дня':'дней'}
function fmtStreak(){return `🔥 ${S.streak} ${dayWord(S.streak)}`}
function progress(){return Object.keys(S.completed).length}
function xpFor(i){return i>=111?50:(i%10===0?20:(i%5===0?15:10))}
function noteToText(m){const n=((m%12)+12)%12;return ['до','до♯','ре','ре♯','ми','фа','фа♯','соль','соль♯','ля','ля♯','си'][n]}
function russianOctave(m){return Math.floor(m/12)-1}
function nav(id){$$('.screen').forEach(x=>x.classList.remove('active'));$('#'+id).classList.add('active');$$('nav button').forEach(x=>x.classList.toggle('active',x.dataset.nav===id));window.scrollTo(0,0);render(id)}
function render(id){touch();$('#streak').textContent=fmtStreak();if(id==='home')home();if(id==='course')course();if(id==='practice')practice();if(id==='songs')songs();}
function home(){const done=progress();const next=Math.min(115,done+1);$('#home').innerHTML=`<div class="hero"><small>ТВОЙ ПУТЬ К ПИАНИНО</small><h1>Научись играть<br><em>с нуля.</em></h1><p>115 полноценных уроков: ноты, ритм, техника, аккорды, гаммы, две руки и песни.</p><button id="micBtn">🎙 Разрешить микрофон</button><div id="micStatus">Микрофон нужен для проверки сыгранных нот.</div></div><div class="card"><div><span>Прогресс курса</span><b>${done} / 115</b></div><div class="bar"><i style="width:${done/115*100}%"></i></div><small>${S.xp} XP • максимум растёт вместе с курсом</small><div class="mini"><span>Пройдено <b>${done}</b></span><span>Сегодня <b>${S.todayXP} XP</b></span></div></div><button class="lesson" id="continueLesson"><strong>🎹</strong><div><small>СЛЕДУЮЩИЙ УРОК</small><h2>${LESSON_TITLES[next-1]}</h2><p>Урок ${next} из 115</p></div><span>›</span></button><h2 class="title">Разделы</h2><div class="grid"><button data-go="course">📚<b>115 уроков</b><small>Полный курс от нуля</small></button><button data-go="practice">🎯<b>Практика</b><small>Ноты и аккорды</small></button><button data-go="songs">🎵<b>Песни</b><small>Учить по шагам</small></button></div>`;$('#continueLesson').onclick=()=>openLesson(next);$('#micBtn').onclick=startMic;$$('[data-go]').forEach(b=>b.onclick=()=>nav(b.dataset.go))}
function course(){let html=`<div class="head"><div><small>ПОЛНЫЙ КУРС</small><h1>115 уроков</h1></div></div><div class="level"><div><small>ПРОГРЕСС</small><h2>${progress()} / 115</h2><p class="muted">От первых нот до полноценной песни.</p></div><b>🎹</b></div>`;LESSON_TITLES.forEach((t,i)=>{const n=i+1,done=S.completed[n];html+=`<button class="lessonRow ${done?'done':''}" data-lesson="${n}"><i>${done?'✓':n}</i><div><small>${phase(n)}</small><h3>${t}</h3><p>${metaFor(n)}</p></div><span>›</span></button>`});$('#course').innerHTML=html;$$('[data-lesson]').forEach(b=>b.onclick=()=>openLesson(+b.dataset.lesson))}
function phase(n){if(n<=10)return'СТАРТ';if(n<=20)return'РИТМ';if(n<=30)return'ТЕХНИКА';if(n<=40)return'НОТЫ';if(n<=60)return'АККОРДЫ';if(n<=70)return'ГАММЫ';if(n<=80)return'ТЕХНИКА';if(n<=90)return'СОПРОВОЖДЕНИЕ';if(n<=100)return'МУЗЫКАЛЬНОСТЬ';return'ПЕСНИ'}
function metaFor(n){const t=LESSON_TITLES[n-1];if([1,2,3,4,5].includes(n))return'Короткая теория + визуальная практика';if(n===64)return'Фа мажор: ноты, чёрная клавиша и аппликатура';if(n>=101)return'Пошаговый разбор + практика обеих рук';return`${Math.round(2+n%4)} мин • практика с подсказками`}
function openLesson(n){nav('lesson');renderLesson(n)}
function renderLesson(n){const t=LESSON_TITLES[n-1],sp=SPECIAL[n]||autoLesson(n,t),xp=xpFor(n);$('#lesson').innerHTML=`<div class="head"><button id="backCourse">‹</button><div><small>УРОК ${n} ИЗ 115</small><h1>${t}</h1></div></div><div class="duration"><span>⏱ ${2+n%5} мин</span><b>+${xp} XP</b></div><div class="lessonVisual">${visual(sp.visual,n)}<b>${visualTitle(sp.visual,t)}</b><small>${sp.type==='song'?'Слушай → разбирай → играй':'Сначала пойми, потом сыграй'}</small></div><div class="lessonBox"><span>ТЕОРИЯ</span><h2>Главное на сегодня</h2><p>${sp.theory}</p></div><div class="steps"><b>Практика</b><br>${sp.practice}</div>${extraLesson(n,sp)}<div id="exercise"></div><button class="primary" id="startExercise">▶ Начать практику</button><button class="secondary" id="finishLesson">✓ Завершить урок</button>`;$('#backCourse').onclick=()=>nav('course');$('#startExercise').onclick=()=>startExercise(n,sp);$('#finishLesson').onclick=()=>finishLesson(n,xp)}
function autoLesson(n,t){let type='practice',theory='',practice='',visual='practice';if(n<=10){type=n===7?'rhythm':'notes';visual=n===7?'rhythm':'keyboard';theory=n===7?'Ритм — это порядок длительностей и акцентов. Сначала считаем вслух, потом переносим счёт на клавиши.':`Сегодня тренируем тему «${t.toLowerCase()}» маленькими шагами. Не спеши: точность важнее скорости.`;practice=n===7?'Хлопни или простучи 4 ровных доли, затем сыграй одну ноту на первую долю.':'Повтори короткую последовательность, которую показывает приложение.'}else if(n<=40){visual=n%3===0?'staff':'hands';theory=`Разберём «${t.toLowerCase()}» на одном простом примере. Запомни только правило, которое нужно прямо сейчас.`;practice='Сделай короткое упражнение и повтори его без подсказки.'}else if(n<=60){type='chord';visual='chord';theory=`Тема урока — «${t.toLowerCase()}». Сначала увидишь форму аккорда, затем сыграешь её несколько раз в разных тональностях.`;practice='Приложение само выберет следующий аккорд. Твоя задача — найти его на русской клавиатуре и сыграть одновременно.'}else if(n<=70){type='scale';visual='scale';theory=`Разбираем «${t.toLowerCase()}» простым языком: какие ноты входят, где находятся чёрные клавиши и как двигать пальцами.`;practice='Сыграй гамму медленно вверх и вниз, следя за аппликатурой.'}else if(n<=80){type=n===71?'arpeggio':'practice';visual=n===71?'arpeggio':'hands';theory=`Тема — «${t.toLowerCase()}». Здесь важнее движение пальцев и ровный звук, чем скорость.`;practice='Повтори движение 4 раза, затем один раз без подсказки.'}else if(n<=90){type='left';visual='hands';theory=`Сегодня левая рука учится быть опорой. Разберём «${t.toLowerCase()}» и сразу применим его к маленькой музыкальной фразе.`;practice='Сыграй бас левой рукой, затем добавь простую правую партию.'}else if(n<=100){type='practice';visual=n===88?'pedal':'rhythm';theory=`Разберём музыкальный навык «${t.toLowerCase()}». Короткая теория — только то, что понадобится в упражнении.`;practice='Сделай упражнение медленно, затем повтори его без визуальной подсказки.'}else{type='song';visual='song';theory=`Это часть песенного блока: «${t.toLowerCase()}». Здесь теория сразу превращается в музыкальную практику.`;practice='Послушай фрагмент, разучи маленькую часть и соедини её с предыдущей.'}return{type,theory,practice,visual}}
function visual(type,n){if(type==='keyboard')return`<div class="runSymbol">🎹</div><div class="piano miniPiano" id="visualPiano"></div>`;if(type==='seat')return'<div class="runSymbol">🧍‍♂️</div><div class="tag gold">спина</div><div class="tag">плечи</div><div class="tag">локти</div><div class="tag">кисти</div><div class="tag">стопы</div>';if(type==='hands')return'<div class="twoHand"><span>🤚 Правая рука<br>мелодия</span><span>🤚 Левая рука<br>опора</span></div>';if(type==='chord')return'<div class="runSymbol">🎹</div><div class="tag gold">3 клавиши одновременно</div>';if(type==='scale')return'<div class="runSymbol">↗️</div><div class="tag">вверх</div><div class="tag">вниз</div><div class="tag gold">аппликатура</div>';if(type==='arpeggio')return'<div class="runSymbol">〰️</div><div class="tag gold">по одной ноте</div>';if(type==='rhythm')return'<div class="runSymbol">🥁</div><div class="tag gold">1 · 2 · 3 · 4</div>';if(type==='pedal')return'<div class="runSymbol">🦶</div><div class="tag gold">смена педали</div>';if(type==='timer')return'<div class="runSymbol">⏱️</div>';if(type==='song')return'<div class="runSymbol">🎵</div><div class="tag gold">слушай → играй</div>';return'<div class="runSymbol">🎯</div><div class="tag gold">точность > скорость</div>'}
function visualTitle(type,t){const m={keyboard:'Клавиатура в деле',seat:'Проверь положение тела',hands:'Две руки — две роли',chord:'Форма аккорда',scale:'Движение по гамме',arpeggio:'Ноты аккорда по очереди',rhythm:'Почувствуй пульс',pedal:'Нога помогает звуку',timer:'Короткая тренировка',song:'Музыка вместо сухой теории',practice:'Сделай и сразу услышишь'};return m[type]||t}
function extraLesson(n,sp){let h='';if([14,31,41,51,64,71,88,91,111].includes(n)){const tips={14:'Не смотри на каждую клавишу. После нескольких повторов попробуй смотреть чуть вперед, а не под пальцы.',31:'На стане важнее сначала узнать направление мелодии, чем мгновенно читать каждую ноту.',41:'Лайфхак: думай о трезвучии как о «через одну белую клавишу» — для До мажора это до–ми–соль.',51:'Лайфхак: в миноре средняя нота трезвучия опускается на полтона. Сравни До мажор и До минор.',64:'Лайфхак: у Фа мажора только одна чёрная клавиша — си-бемоль. Остальные ноты белые.',71:'Лайфхак: арпеджио — это тот же аккорд, только ноты идут по очереди.',88:'Не держи педаль бесконечно. Смена гармонии — хороший момент обновить её.',91:'Лучше 15 минут с целью, чем час без плана.',111:'Сначала играй медленно. Скорость появится после точности.'};if(tips[n])h=`<div class="tip">💡 <b>Полезный приём</b><br>${tips[n]}</div>`}return h}
function startExercise(n,sp){const box=$('#exercise');let html='';if(sp.type==='notes'||n<=2){html=noteExercise(n)}else if(sp.type==='chord'){html=chordExercise()}else if(sp.type==='scale'){html=scaleExercise(n)}else if(sp.type==='song'){html=songExercise(n)}else if(sp.type==='seat'){html=seatExercise()}else if(sp.type==='hands'){html=handExercise()}else if(sp.type==='rhythm'){html=rhythmExercise()}else{html=genericExercise(n)}box.innerHTML=html;initExercise(n,sp);$('#startExercise').remove()}
function piano(start=60,end=72,target=[]){let h='<div class="piano">';for(let m=start;m<=end;m++){const nm=noteToText(m);const black=[1,3,6,8,10].includes(m%12);h+=`<button class="pkey ${black?'black':''} ${target.includes(m)?'target dot':''}" data-midi="${m}" title="${nm} ${russianOctave(m)}">${black?'':nm}</button>`}return h+'</div>'}
function noteExercise(n){const seq=n===1?NOTE_NAMES:NOTE_NAMES.slice(0,5);return`<div class="explain"><b>Найди и сыграй: <span id="targetNote">${seq[0]}</span></b><p>На клавиатуре ниже подсветится нужная нота. Нажимай её. Микрофон можно включить для проверки настоящего синтезатора.</p></div>${piano(60,72)}<div class="detector" id="noteFeedback"><i></i><b>Жду ноту</b><small>Можно играть на своём синтезаторе</small></div>`}
function chordExercise(){return`<div class="chordBig"><small>СЫГРАЙ СЛЕДУЮЩИЙ АККОРД</small><b id="chordName">До мажор</b><span id="chordNotes">до · ми · соль</span></div>${piano(48,72)}<div class="detector" id="chordFeedback"><i></i><b>Три клавиши вместе</b><small>Приложение само выбрало аккорд</small></div>`}
function scaleExercise(n){const scale=n===64?['фа','соль','ля','си♭','до','ре','ми','фа']:['до','ре','ми','фа','соль','ля','си','до'];return`<div class="explain"><b>Гамма</b><p>${scale.join(' → ')}</p></div>${piano(60,72)}<div class="detector" id="scaleFeedback"><i></i><b>Начни с первой ноты</b><small>Играем медленно вверх</small></div>`}
function songExercise(n){return`<div class="iframeWrap"><iframe src="https://www.youtube.com/embed/8sh31m-QBvU?rel=0" title="Spring piano" allow="accelerometer;autoplay;clipboard-write;encrypted-media;gyroscope;picture-in-picture" allowfullscreen></iframe></div><button class="primary" id="songPractice">🎹 Играть учебный фрагмент</button><div class="falling"><div class="fallNote">♪</div><div class="hitLine">ЗОНА ИГРЫ</div></div><div class="targets"><div><small>ПРАВАЯ</small><b>мелодия</b></div><div><small>ЛЕВАЯ</small><b>опора</b></div></div>`}
function seatExercise(){return`<div class="checklist"><label><input type="checkbox">Стопы стоят устойчиво</label><label><input type="checkbox">Плечи расслаблены</label><label><input type="checkbox">Локти примерно на уровне клавиш</label><label><input type="checkbox">Кисти не провалены</label><label><input type="checkbox">Я не тянусь к клавиатуре</label></div><button class="secondary" id="seatDone">✓ Проверить посадку</button><div class="feedback" id="seatFeedback">Отметь пять пунктов.</div>`}
function handExercise(){return`<div class="twoHand"><div class="hand">Правая<br><b>до–ре–ми–фа–соль</b></div><div class="hand">Левая<br><b>до–ре–ми–фа–соль</b></div></div>${piano(60,72)}<div class="feedback">Сначала отдельно каждой рукой. Затем вместе на очень медленной скорости.</div>`}
function rhythmExercise(){return`<div class="runCard"><small>СЧЁТ</small><b id="beat">1</b><p>Нажимай «Старт» и держи ровный пульс.</p><button class="primary" id="beatStart">▶ Старт</button></div><div class="feedback" id="rhythmFeedback">Не гонись за скоростью. Ровность важнее.</div>`}
function genericExercise(n){return`<div class="runCard"><small>МИНИ-УПРАЖНЕНИЕ</small><b>${n}</b><p>Сделай 4 повторения медленно, затем одно без подсказки.</p><button class="primary" id="genericStart">▶ Выполнено</button></div><div class="feedback" id="genericFeedback">После выполнения отметь урок завершённым.</div>`}
function initExercise(n,sp){$$('.pkey').forEach(k=>k.onclick=()=>{k.classList.add('hit');setTimeout(()=>k.classList.remove('hit'),250);const f=$('#noteFeedback');if(f){f.innerHTML='<i></i><b>Отлично!</b><small>Нота сыграна на виртуальной клавиатуре</small>';nextNoteIfNeeded(n)}});if($('#seatDone'))$('#seatDone').onclick=()=>$('#seatFeedback').textContent=$$('.checklist input:checked').length===5?'Отлично. Посадка проверена.':'Проверь все пять пунктов.';if($('#beatStart')){let b=0;$('#beatStart').onclick=()=>{const id=setInterval(()=>{b++;$('#beat').textContent=((b-1)%4)+1;if(b>=9){clearInterval(id);$('#rhythmFeedback').textContent='Ровно! Теперь попробуй то же самое на клавишах.'}},600)}}if($('#genericStart'))$('#genericStart').onclick=()=>{$('#genericFeedback').textContent='Готово. Теперь попробуй повторить ещё раз без подсказки.'};if($('#songPractice'))$('#songPractice').onclick=()=>alert('Учебный режим песни подготовлен: сначала правая рука, затем левая, затем соединение.');if(sp.type==='chord')setRandomChord();}
let currentNoteIndex=0;function nextNoteIfNeeded(n){if(n!==1&&n!==2)return;const seq=n===1?NOTE_NAMES:NOTE_NAMES.slice(0,5);currentNoteIndex++;if(currentNoteIndex>=seq.length){currentNoteIndex=0;$('#noteFeedback').innerHTML='<i></i><b>Серия закончена!</b><small>Ты прошёл все ноты этого шага</small>'}else{$('#targetNote').textContent=seq[currentNoteIndex]}}
let micStream=null,audioCtx=null,analyser=null;async function startMic(){try{if(micStream){micStream.getTracks().forEach(t=>t.stop());micStream=null;$('#micStatus').textContent='Микрофон остановлен';return}micStream=await navigator.mediaDevices.getUserMedia({audio:{echoCancellation:false,noiseSuppression:false,autoGainControl:false}});audioCtx=new AudioContext();const src=audioCtx.createMediaStreamSource(micStream);analyser=audioCtx.createAnalyser();analyser.fftSize=4096;src.connect(analyser);$('#micStatus').textContent='🎙 Микрофон слушает синтезатор';detectPitch()}catch(e){$('#micStatus').textContent='Не удалось получить доступ к микрофону'}}
function detectPitch(){if(!analyser)return;const data=new Float32Array(analyser.fftSize);analyser.getFloatTimeDomainData(data);let rms=Math.sqrt(data.reduce((s,x)=>s+x*x,0)/data.length);if(rms>.01){let bestLag=0,best=-1;for(let lag=20;lag<500;lag++){let c=0;for(let i=0;i<data.length-lag;i+=4)c+=data[i]*data[i+lag];if(c>best){best=c;bestLag=lag}}if(bestLag){const freq=audioCtx.sampleRate/bestLag;const midi=Math.round(69+12*Math.log2(freq/440));const text=noteToText(midi);const f=$('#noteFeedback');if(f){f.innerHTML=`<i></i><b>${text}</b><small>${russianOctave(midi)} октава • услышано микрофоном</small>`}}}requestAnimationFrame(detectPitch)}
function randomChord(){const root=ROOTS[Math.floor(Math.random()*ROOTS.length)];const type=['мажор','минор','sus4'][Math.floor(Math.random()*3)];return {root,type}}
function chordMidi(root,type){const base=KEY_MIDI[root],ints=type==='мажор'?[0,4,7]:type==='минор'?[0,3,7]:[0,5,7];return ints.map(x=>base+x)}
function setRandomChord(){const c=randomChord();const ms=chordMidi(c.root,c.type);$('#chordName').textContent=`${c.root} ${c.type}`;$('#chordNotes').textContent=ms.map(noteToText).join(' · ');$$('.pkey').forEach(k=>k.classList.toggle('target',ms.includes(+k.dataset.midi)))}
function finishLesson(n,xp){if(!S.completed[n]){S.completed[n]=true;S.xp+=xp;S.todayXP+=xp;saveState()}nav('course')}
function practice(){ $('#practice').innerHTML=`<div class="head"><div><small>ТРЕНИРОВКА</small><h1>Практика</h1></div></div><div class="tabs"><button class="active" data-tab="notes">🎹 Ноты</button><button data-tab="chords">🎼 Аккорды</button></div><div id="practiceBody"></div>`;$$('[data-tab]').forEach(b=>b.onclick=()=>{$$('[data-tab]').forEach(x=>x.classList.remove('active'));b.classList.add('active');practiceBody(b.dataset.tab)});practiceBody('notes')}
function practiceBody(tab){const b=$('#practiceBody');if(tab==='notes'){b.innerHTML=`<div class="explain"><b>Рандомная нота</b><p>Приложение само выбирает ноту. Сначала найди её на виртуальной клавиатуре, потом попробуй сыграть её на своём синтезаторе через микрофон.</p></div><div class="noteAnim"><div class="staff"><span id="practiceGlyph">♪</span></div><b id="practiceNote">до</b><small>без английских обозначений</small></div>${piano(60,72)}<div class="detector" id="practiceFeedback"><i></i><b>Жду ноту</b><small>Нажми «Новая нота»</small></div><button class="primary" id="newNote">🎲 Новая нота</button>`;$('#newNote').onclick=()=>{const n=NOTE_NAMES[Math.floor(Math.random()*7)];$('#practiceNote').textContent=n;$$('.pkey').forEach(k=>k.classList.remove('target'));const mids=Object.values(KEY_MIDI);const m=KEY_MIDI[n];const key=$(`.pkey[data-midi="${m}"]`);if(key)key.classList.add('target')};$$('.pkey').forEach(k=>k.onclick=()=>{$('#practiceFeedback').innerHTML='<i></i><b>Верно!</b><small>Попробуй сыграть ту же ноту на синтезаторе</small>'})}else{b.innerHTML=`<div class="chordTypes"><button class="active" data-ct="мажор">Мажор</button><button data-ct="минор">Минор</button><button data-ct="уменьшенный">Уменьш.</button><button data-ct="sus4">Sus4</button></div><div class="chordBig"><small>РЕЖИМ</small><b id="practiceChord">До мажор</b><span id="practiceChordNotes">до · ми · соль</span></div>${piano(48,72)}<div class="detector" id="chordPracticeFeedback"><i></i><b>Сыграй аккорд</b><small>Конкретный аккорд выбирается автоматически</small></div><button class="primary" id="newChord">🎲 Следующий аккорд</button>`;let ct='мажор';$$('[data-ct]').forEach(x=>x.onclick=()=>{$$('[data-ct]').forEach(y=>y.classList.remove('active'));x.classList.add('active');ct=x.dataset.ct;nextChord(ct)});$('#newChord').onclick=()=>nextChord(ct);function nextChord(type){let root=ROOTS[Math.floor(Math.random()*ROOTS.length)];let ints=type==='мажор'?[0,4,7]:type==='минор'?[0,3,7]:type==='sus4'?[0,5,7]:[0,3,6];let ms=ints.map(i=>KEY_MIDI[root]+i);$('#practiceChord').textContent=`${root} ${type}`;$('#practiceChordNotes').textContent=ms.map(noteToText).join(' · ');$$('.pkey').forEach(k=>k.classList.toggle('target',ms.includes(+k.dataset.midi)))}nextChord(ct)}}
function songs(){let h=`<div class="head"><div><small>БИБЛИОТЕКА</small><h1>Песни</h1></div></div><p class="muted">Сначала послушай пример, затем разбирай песню по маленьким частям. Видео открываются прямо внутри приложения.</p>`;SONGS.forEach(s=>h+=`<button class="song" data-song="${s.id}"><div class="cover">🎵</div><div><h3>${s.name}</h3><p>${s.artist} • ${s.level}</p><strong>▶ Послушать пример</strong></div><span>›</span></button>`);$('#songs').innerHTML=h;$$('[data-song]').forEach(b=>b.onclick=()=>openSong(b.dataset.song))}
function openSong(id){const s=SONGS.find(x=>x.id===id);nav('song');$('#song').innerHTML=`<div class="head"><button id="backSongs">‹</button><div><small>ПЕСНЯ</small><h1>${s.name}</h1></div></div><div class="songHero"><div>🎵</div><div><h2>${s.artist}</h2><p>${s.desc}</p>${s.tags.map(t=>`<span class="tag">${t}</span>`).join('')}</div></div><div class="iframeWrap"><iframe src="https://www.youtube.com/embed/${s.video}?rel=0" title="${s.name}" allow="accelerometer;autoplay;clipboard-write;encrypted-media;gyroscope;picture-in-picture" allowfullscreen></iframe></div><div class="explain"><b>Как учить</b><p>1. Послушай пример. 2. Разучи правую руку. 3. Добавь левую. 4. Соедини медленно. 5. Увеличивай темп только после нескольких чистых повторов.</p></div><button class="primary" id="songStart">🎹 Начать обучение</button><div class="falling"><div class="fallNote">♪</div><div class="hitLine">ЗОНА ИГРЫ</div></div><div class="feedback">В следующей версии музыкального режима сюда можно подключить MIDI/аудио-сопровождение без зависимости от автозапуска YouTube.</div>`;$('#backSongs').onclick=()=>nav('songs');$('#songStart').onclick=()=>alert('Начинаем с маленького фрагмента. Играй медленно и только потом ускоряйся.')}
$$('nav button').forEach(b=>b.onclick=()=>nav(b.dataset.nav));nav('home');
